# Generated by Django 4.0.4 on 2022-05-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.IntegerField()),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=30)),
                ('description', models.TextField(default='no description', max_length=1000)),
                ('for_vip', models.BooleanField(default=0)),
                ('for_city', models.BooleanField(default=0)),
                ('for_real', models.BooleanField(default=0)),
                ('for_united', models.BooleanField(default=0)),
                ('for_barcelona', models.BooleanField(default=0)),
            ],
        ),
    ]
