# Generated by Django 3.2.7 on 2021-09-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='photo',
            field=models.CharField(default='https://www.freeiconspng.com/uploads/no-image-icon-4.png', max_length=255),
        ),
    ]
