# Generated by Django 3.2.7 on 2021-09-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_merch_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
