# Generated by Django 3.2.7 on 2021-09-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0005_alter_merch_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='photo',
        ),
    ]
