# Generated by Django 3.2.7 on 2021-09-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0012_merchbarcelona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchBarcelona',
        ),
    ]
