# Generated by Django 3.2.7 on 2021-09-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0013_delete_merchbarcelona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='merch',
            name='for_barcelona',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='merch',
            name='for_city',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='merch',
            name='for_real',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='merch',
            name='for_united',
            field=models.BooleanField(default=0),
        ),
    ]
