# Generated by Django 3.2.7 on 2021-09-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0014_auto_20210920_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchManUnited',
        ),
    ]
