# Generated by Django 3.2.7 on 2021-09-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0015_delete_merchmanunited'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchReal',
        ),
    ]
