# Generated by Django 3.2.7 on 2021-09-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0016_delete_merchreal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='updated_at',
        ),
    ]
