# Generated by Django 3.2.7 on 2021-09-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0017_auto_20210920_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
