# Generated by Django 3.2.7 on 2021-09-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vip',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vip',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vip',
            name='price',
        ),
        migrations.RemoveField(
            model_name='vip',
            name='title',
        ),
        migrations.RemoveField(
            model_name='vip',
            name='updated_at',
        ),
    ]
