# Generated by Django 3.2.7 on 2021-09-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210914_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VIP',
        ),
    ]
