# Generated by Django 4.0.4 on 2022-05-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_man_city', models.CharField(blank=True, max_length=150, null=True)),
                ('match_info_man_city', models.CharField(blank=True, max_length=150, null=True)),
                ('title_real_madrid', models.CharField(blank=True, max_length=150, null=True)),
                ('match_info_real_madrid', models.CharField(blank=True, max_length=150, null=True)),
                ('title_man_united', models.CharField(blank=True, max_length=150, null=True)),
                ('match_info_man_united', models.CharField(blank=True, max_length=150, null=True)),
                ('title_barcelona', models.CharField(blank=True, max_length=150, null=True)),
                ('match_info_barcelona', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
