# Generated by Django 3.2.6 on 2021-09-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0003_fixture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fixture',
        ),
    ]
