# Generated by Django 3.2.6 on 2021-09-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0005_fixture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fixture',
        ),
    ]
