# Generated by Django 3.2.6 on 2021-09-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixture', '0006_delete_fixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureMancity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
