# Generated by Django 3.2.7 on 2021-09-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0009_rename_fixturemanunited_fixturerealmadrid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_man_city', models.CharField(max_length=150)),
                ('match_info_man_city', models.CharField(max_length=150)),
                ('title_real_madrid', models.CharField(max_length=150)),
                ('match_info_real_madrid', models.CharField(max_length=150)),
                ('title_man_united', models.CharField(max_length=150)),
                ('match_info_man_united', models.CharField(max_length=150)),
                ('title_barcelona', models.CharField(max_length=150)),
                ('match_info_barcelona', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
