# Generated by Django 3.2.7 on 2021-09-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0010_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='match_info_barcelona',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='match_info_man_city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='match_info_man_united',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='match_info_real_madrid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='title_barcelona',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='title_man_city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='title_man_united',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='title_real_madrid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
