# Generated by Django 3.2.7 on 2021-09-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0011_auto_20210920_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fixture',
        ),
    ]
