# Generated by Django 3.2.7 on 2021-09-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0013_fixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureBarcelona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FixtureManUnited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
