# Generated by Django 3.2.7 on 2021-09-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0015_auto_20210920_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FixtureBarcelona',
        ),
        migrations.DeleteModel(
            name='FixtureMancity',
        ),
        migrations.DeleteModel(
            name='FixtureManUnited',
        ),
        migrations.DeleteModel(
            name='FixtureRealMadrid',
        ),
    ]
