# Generated by Django 4.0.4 on 2022-05-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalityPayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(blank=True, max_length=150, null=True)),
                ('price_city', models.IntegerField(blank=True, help_text='price in euro', null=True)),
                ('description_city', models.TextField(blank=True, default='no description', max_length=800, null=True)),
                ('name_barcelona', models.CharField(blank=True, max_length=150, null=True)),
                ('price_barcelona', models.IntegerField(blank=True, help_text='price in euro', null=True)),
                ('description_barcelona', models.TextField(blank=True, default='no description', max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalityVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_real', models.CharField(blank=True, max_length=150, null=True)),
                ('description_real', models.TextField(blank=True, default='no description', max_length=800, null=True)),
                ('name_united', models.CharField(blank=True, max_length=150, null=True)),
                ('description_united', models.TextField(blank=True, default='no description', max_length=800, null=True)),
            ],
        ),
    ]
