# Generated by Django 3.2.6 on 2021-09-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0002_alter_hospitality_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalityReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField(help_text='price in euro')),
                ('description', models.TextField(default='no description', max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
