# Generated by Django 3.2.7 on 2021-09-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0003_hospitalityreal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitality',
            name='description',
            field=models.TextField(default='no description', max_length=800, null=True),
        ),
    ]
