# Generated by Django 3.2.7 on 2021-09-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0005_remove_hospitalityreal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalityreal',
            name='available_date',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
