# Generated by Django 3.2.7 on 2021-09-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0006_hospitalityreal_available_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalityreal',
            name='available_date',
        ),
    ]
