# Generated by Django 3.2.7 on 2021-09-15 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0007_remove_hospitalityreal_available_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='hospitalityreal',
            name='available_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitality.availabledate'),
        ),
    ]
