# Generated by Django 3.2.7 on 2021-09-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0008_auto_20210915_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalityreal',
            name='available_date',
        ),
    ]
