# Generated by Django 3.2.7 on 2021-09-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0009_remove_hospitalityreal_available_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabledate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='availabledate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hospitality',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hospitality',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hospitalityreal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hospitalityreal',
            name='updated_at',
        ),
    ]
