# Generated by Django 3.2.7 on 2021-09-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0012_auto_20210923_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalityPayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=150)),
                ('price_city', models.IntegerField(help_text='price in euro')),
                ('description_city', models.TextField(default='no description', max_length=800, null=True)),
                ('name_barcelona', models.CharField(max_length=150)),
                ('price_barcelona', models.IntegerField(help_text='price in euro')),
                ('description_barcelona', models.TextField(default='no description', max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalityVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_real', models.CharField(max_length=150)),
                ('description_real', models.TextField(default='no description', max_length=800)),
                ('name_united', models.CharField(max_length=150)),
                ('description_united', models.TextField(default='no description', max_length=800)),
            ],
        ),
    ]
