# Generated by Django 3.2.7 on 2021-09-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0013_hospitalitypayed_hospitalityvip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalitypayed',
            name='description_barcelona',
            field=models.TextField(blank=True, default='no description', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalitypayed',
            name='description_city',
            field=models.TextField(blank=True, default='no description', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalitypayed',
            name='name_barcelona',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalitypayed',
            name='name_city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalitypayed',
            name='price_barcelona',
            field=models.IntegerField(blank=True, help_text='price in euro', null=True),
        ),
        migrations.AlterField(
            model_name='hospitalitypayed',
            name='price_city',
            field=models.IntegerField(blank=True, help_text='price in euro', null=True),
        ),
        migrations.AlterField(
            model_name='hospitalityvip',
            name='description_real',
            field=models.TextField(blank=True, default='no description', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalityvip',
            name='description_united',
            field=models.TextField(blank=True, default='no description', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalityvip',
            name='name_real',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalityvip',
            name='name_united',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
