# Generated by Django 3.2.7 on 2021-09-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_product_cartitem_merch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='merch',
            new_name='product',
        ),
    ]
